# Generated by Django 5.2.1 on 2025-06-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='specialist_profile_pic'),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='specialist_id',
            field=models.CharField(blank=True, help_text='Required if not affiliated with a hospital', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='specialistprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='core_app.hospital'),
        ),
    ]
